[project]
name = "finam-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "finam-trade-api>=4.1.0",
    "grpcio-tools>=1.75.0",
    "mcp[cli]>=1.14.1",
]
